// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Comment events are generated by staff members of a shop.
  /// They are created when a staff member adds a comment to the timeline of an order, draft order, customer, or transfer.
  static let CommentEvent = ApolloAPI.Object(
    typename: "CommentEvent",
    implementedInterfaces: [
      Interfaces.Event.self,
      Interfaces.Node.self
    ],
    keyFields: nil
  )
}